### ISSUE TITLE
Comments are parsed as strings

### ISSUE THREAD

**Issue by AdamGaskins** [ansballard/language-asp#1]
Asp/vbscript single-line comments are denoted with the single quote character (`'`), however they are being parsed as strings:

![1416581530](https://cloud.githubusercontent.com/assets/1180782/5143997/29babcee-7164-11e4-8a2f-ccbf41a52b23.png)

Side note: I really appreciate you putting together this project, it was exactly what I was looking for.

**Comment by taludelito** [comment]
> Texto Sublime 3

it appears that this problem is no longer occurring in Sublime Text 3.
also does not occur on the equivalent atom with php

**Comment by taludelito** [comment]
centralizing the discussion and solution here [https://github.com/FluidCoding/improved-asp-html/issues/3]
