### ISSUE TITLE
Repo Ownership

### ISSUE THREAD

**Issue by ansballard** [ansballard/language-asp#7]
Was just running through my atom packages and saw you were looking to pass on ownership for this one. I haven't actually played with language packages for atom, but I'd be happy to take it on, if only to help any other poor souls still using ASP that might find a bug here.

I'm currently maintaining minimap-autohider, so I have a good idea of what's involved in supporting an atom package, at least for small user groups. Let me know if I can help!

**Comment by trickierstinky** [comment]
Oh, you'd be taking a load of my hand doing so, I hate not being able to put the time in to support users who still use it!

**Comment by ansballard** [comment]
Happy to hear it! I've pulled the repo over, made the necessary changes to `package.json`, and published a new version with apm that seems to have pushed out just fine, so we should be good to go!
